# docker-compose.yml
services:
  ocr-api:
    build: .
    ports:
      - "9876:5000"
    volumes:
      - ocr-data:/data
      - paddleocr-models:/root/.paddleocr
      - huggingface-models:/root/.cache/huggingface
      - doctr-models:/root/.cache/doctr
    environment:
      - TZ=Europe/Paris
      - PORT=5000
      - FLASK_DEBUG=False
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:5000 app:app --timeout 300 --workers 1

volumes:
  ocr-data:
  paddleocr-models:
  huggingface-models:
  doctr-models: